<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>mblue_test</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup Condition="Exists('../../mblue-common/src/mblue_common.csproj')">
  <ProjectReference Include="../../mblue-common/src/mblue_common.csproj" />
</ItemGroup>
<ItemGroup Condition="!Exists('../../mblue-common/src/mblue_common.csproj')">
  <PackageReference Include="mblue_common" Version="*" />
</ItemGroup>

</Project>
